# Generated by Django 4.1.7 on 2023-03-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_spending_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concretecategory',
            name='limit',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AlterField(
            model_name='spending',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='spending',
            name='photo',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
