# Generated by Django 5.0.6 on 2024-11-05 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_spending_tracker', '0002_alter_concretecategory_limit_alter_spending_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
