# Generated by Django 5.0.6 on 2024-11-05 23:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_spending_tracker', '0003_alter_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=25, unique=True, validators=[django.core.validators.RegexValidator(message='Username must contain at least 5 characters', regex='^.{5,}$')]),
        ),
    ]
